### ISSUE TITLE
500 - Palvelinvirhe avattaessa uutta tietopyyntöä

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#92]
![screenshot 2016-03-01 19 51 44](https://cloud.githubusercontent.com/assets/3482497/13436274/1905b2da-dfe7-11e5-8122-31dc0d6f2e5a.png)

http://tietopyynto.fi/tee-tietopyynto/vastaanottaja/kemionsaaren-vesi/

**Comment by jaakkokorhonen** [comment]
viranomaisen luomisessa jotain vikaa?

**Comment by hylje** [comment]
Mulle tuli tästä läjä virheilmotuksia sähköpostiin, tutkin tarkemmin missä vika myöhemmin. Vaikuttaa alustavasti siltä, että joltain viranomaisella puuttuu lainsäädäntöön liittyvä bitti.

Itse asiassa tässä tapauksessa olleella Kemiönsaaren Vesi-viranomaisella puuttui toimialue (pitäisi olla Suomi)

**Comment by jaakkokorhonen** [comment]
ah. pitäisikö olla pakollinen kenttä?

**Comment by hylje** [comment]
Se voisi olla pakollinen, pistän tän tiketin korvan taakse pysyvämpää korjausta varten. Toistaiseksi varmaan riittää politiikaksi muistaa lisätä toimialuekenttään arvo.

```
Internal Server Error: /api/v1/publicbody/search/
Traceback (most recent call last):
 File "/home/django/tietopyynto/env2/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
   response = callback(request, *args, **kwargs)
 File "/home/django/tietopyynto/froide-new/froide/publicbody/api.py", line 204, in get_search
   bundle = self.full_dehydrate(bundle)
 File "/home/django/tietopyynto/env2/lib/python2.7/site-packages/tastypie/resources.py", line 853, in full_dehydrate
   bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
 File "/home/django/tietopyynto/env2/lib/python2.7/site-packages/tastypie/fields.py", line 723, in dehydrate
   foreign_obj = getattr(foreign_obj, attr, None)
 File "/home/django/tietopyynto/froide-new/froide/publicbody/models.py", line 328, in default_law
   return FoiLaw.get_default_law(self)
 File "/home/django/tietopyynto/froide-new/froide/publicbody/models.py", line 151, in get_default_law
   return cls.objects.filter(jurisdiction=pb.jurisdiction).order_by('-meta')[0]
 File "/home/django/tietopyynto/env2/lib/python2.7/site-packages/django/db/models/query.py", line 201, in __getitem__
   return list(qs)[0]
IndexError: list index out of range
```

```
Internal Server Error: /api/v1/publicbody/autocomplete/
Traceback (most recent call last):
 File "/home/django/tietopyynto/env2/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
   response = callback(request, *args, **kwargs)
 File "/home/django/tietopyynto/froide-new/froide/publicbody/api.py", line 160, in get_autocomplete
   names = [u"%s (%s)" % (x.name, jur_get(x)) for x in sqs]
 File "/home/django/tietopyynto/froide-new/froide/publicbody/api.py", line 156, in jur_get
   return pb.object.jurisdiction.name
AttributeError: 'NoneType' object has no attribute 'name'
```
